# 多模态复发预测与分类多任务模型配置
data:
  num_classes: 2  # 复发预测类别数
  num_classes_subtype: 3  # 肿瘤亚型分类类别数
  output_dir: 'mul_train_output'
  class_names: ['Invasive', 'Non-invasive']
  subtype_class_names: ['低分化', '中分化', '高分化', '原位癌', '微浸润']
  csv_path:
    - "E:\\workplace\\3D\\datasets\\CTreport\\2021_updated.csv"
    - "E:\\workplace\\3D\\datasets\\CTreport\\2022_updated.csv"
    - "E:\\workplace\\3D\\datasets\\CTreport\\2023_updated.csv"
    - "E:\\workplace\\3D\\datasets\\CTreport\\襄阳.csv"
    - "E:\\workplace\\3D\\datasets\\CTreport\\十堰太和肺结节患者信息_updated.csv"
  max_text_length: 512

model:
  params:
    image_size: [96, 96, 96] # 96 * 96 * 96
    patch_size: 8
    dim: 768
    depth: 8
    heads: 8
    mlp_dim: 128
    mlp_num: 2
    pool: 'max' # mean max all
    cpt_num: 5
  bert_model_name: 'E:\workplace\3D\pred_model\bert_chinese'
  tokenizer_path: 'E:\workplace\3D\pred_model\bert_chinese'
  text_feature_dim: 768
  demographic_dim: 4
  fusion_dim: 384
  fusion_transformer_heads: 2
  fusion_transformer_layers: 2

  dropout: 0.5
  prompt_num: 0  # 提示向量数量
  fusion_type: "cls"  # cls  cross_attn

training:
  device: "cuda"
  random_seed: 42
  batch_size: 32  # 降低批次大小以适应多模态
  num_epochs: 20
  num_workers: 2
  use_amp: true
  cache_dataset: True
  warmup_epochs: 3
  warmup_type: "linear"
  max_grad_norm: 1.0
  crop_size: [96, 96, 16]
  augment: true
  pretrained_path: 'E:\workplace\MultiModel\pred_model\rad_dino'
  bert_pretrained_path: 'E:\workplace\3D\pred_model\bert_chinese' # 如果有预训练的BERT模型，可以在这里指定
  frozen1: false # 冻结图像编码器
  frozen2: true # 冻结文本编码器

  decoder: true
  decoder_weight: 1.0
  decoder_num_layers: 4
  decoder_num_heads: 4
  decoder_max_seq_len: 32

losses:
  CrossEntropyLoss:
    enabled: true
    weight: 1.0
    params: {0.3, 0.7}
  FocalLoss:
    enabled: false
    weight: 1.0
    params:
      gamma: 2.0
      alpha: 0.25
  BoundaryFlowLoss:
    enabled: true
    weight: 1.0
    params:
      weight: 0.5
      margin: 0.3
  SimilarityLoss:
    enabled: false
    params:
      low: 0.3
      high: 0.7
  MultitaskLoss:
    enabled: true
    classification_weight: 1.0  # 分类权重
    axis_weight: 0 #   长短经
    contrastive_weight: 0


cross_validation:
  n_splits: 5
  shuffle: true
  negative_ratio: 10
  pos_ratio: 0.1
  minority_multiplier: 10
  use_clustering: false  # 设置为true启用聚类交叉验证
  clustering_method: "kmeans"  # 聚类方法
  feature_extraction_batch_size: 32  # 特征提取时的批次大小

optimizer:
  name: "AdamW"
  params:
    lr: 0.00001
    weight_decay: 0.001

scheduler:
  name: "CosineAnnealingLR"
  params:
    T_max: 20
    eta_min: 5e-6